// This file is auto-generated by scripts/generate-content-indexes.mjs.
// Do not edit manually.

import item0 from "./items/books/clean-architecture.json";
import item1 from "./items/books/henna-ie.json";
import item2 from "./items/books/kinki.json";
import item3 from "./items/books/mino-driven.json";
import item4 from "./items/books/omae-no-shiin.json";
import item5 from "./items/books/ushijima-kun.json";
import item6 from "./items/games/arcaea.json";
import item7 from "./items/games/chunithm.json";
import item8 from "./items/games/ddr.json";
import item9 from "./items/games/genshin-impact.json";
import item10 from "./items/games/maimai.json";
import item11 from "./items/games/minecraft.json";
import item12 from "./items/games/ongeki.json";
import item13 from "./items/games/project-sekai.json";
import item14 from "./items/games/sound-voltex.json";
import item15 from "./items/games/taiko-no-tatsujin.json";
import item16 from "./items/games/the-battle-cats.json";
import item17 from "./items/music/awake-now.json";
import item18 from "./items/music/im-a-mess.json";
import item19 from "./items/music/lapis-lazuli.json";
import item20 from "./items/music/ray.json";
import item21 from "./items/music/sennou.json";
import item22 from "./items/music/serenade.json";
import item23 from "./items/music/trio-dreams.json";
import item24 from "./items/music/ultra-trailer.json";
import item25 from "./items/music/wakaremichi.json";
import item26 from "./items/others/razer.json";
import item27 from "./items/others/scp.json";
import item28 from "./items/video/attack-of-titan.json";
import item29 from "./items/video/evangerion.json";
import item30 from "./items/video/godzilla-minus-one.json";
import item31 from "./items/video/hirogaru-sky-precure.json";
import item32 from "./items/video/kamen-rider-build.json";
import item33 from "./items/video/kamen-rider-ex-aid.json";
import item34 from "./items/video/kamen-rider-w.json";
import item35 from "./items/video/shin-godzilla.json";
import item36 from "./items/video/you-and-idol-precure-movie.json";
import item37 from "./items/video/you-and-idol-precure.json";

export const interestItemEntries = [
  ["clean-architecture", item0],
  ["henna-ie", item1],
  ["kinki", item2],
  ["mino-driven", item3],
  ["omae-no-shiin", item4],
  ["ushijima-kun", item5],
  ["arcaea", item6],
  ["chunithm", item7],
  ["ddr", item8],
  ["genshin-impact", item9],
  ["maimai", item10],
  ["minecraft", item11],
  ["ongeki", item12],
  ["project-sekai", item13],
  ["sound-voltex", item14],
  ["taiko-no-tatsujin", item15],
  ["the-battle-cats", item16],
  ["awake-now", item17],
  ["im-a-mess", item18],
  ["lapis-lazuli", item19],
  ["ray", item20],
  ["sennou", item21],
  ["serenade", item22],
  ["trio-dreams", item23],
  ["ultra-trailer", item24],
  ["wakaremichi", item25],
  ["razer", item26],
  ["scp", item27],
  ["attack-of-titan", item28],
  ["evangerion", item29],
  ["godzilla-minus-one", item30],
  ["hirogaru-sky-precure", item31],
  ["kamen-rider-build", item32],
  ["kamen-rider-ex-aid", item33],
  ["kamen-rider-w", item34],
  ["shin-godzilla", item35],
  ["you-and-idol-precure-movie", item36],
  ["you-and-idol-precure", item37],
] as const;
