// This file is auto-generated by scripts/generate-content-indexes.mjs.
// Do not edit manually.

import item0 from "./items/2020/senirenol.json";
import item1 from "./items/2023/senirenol-chronicle.json";
import item2 from "./items/2024/aviutl-workshop.json";
import item3 from "./items/2024/science-technocrasy.json";
import item4 from "./items/2024/senirenol-restart.json";
import item5 from "./items/2025/bioence-tokyo.json";
import item6 from "./items/2025/flavorful-vision.json";
import item7 from "./items/2025/home-server.json";
import item8 from "./items/2025/senirenol-bloom.json";
import item9 from "./items/2025/taki-plaza-introduction.json";
import item10 from "./items/2025/twin-stars-mythology.json";
import item11 from "./items/2025/ura-unity-workshop.json";
import item12 from "./items/2025/you-and.json";
import item13 from "./items/2026/beyond-ash.json";
import item14 from "./items/2026/made-in-trap.json";
import item15 from "./items/2026/otoge-rush.json";
import item16 from "./items/2026/senirenol-developers-hub.json";
import item17 from "./items/2026/unity-design-workshop.json";
import item18 from "./items/2026/unity-single-scene-template.json";
import item19 from "./items/2026/uraaka-management.json";
import item20 from "./items/2026/web-portfolio-frontend.json";

export const workItemEntries = [
  ["senirenol", item0],
  ["senirenol-chronicle", item1],
  ["aviutl-workshop", item2],
  ["science-technocrasy", item3],
  ["senirenol-restart", item4],
  ["bioence-tokyo", item5],
  ["flavorful-vision", item6],
  ["home-server", item7],
  ["senirenol-bloom", item8],
  ["taki-plaza-introduction", item9],
  ["twin-stars-mythology", item10],
  ["ura-unity-workshop", item11],
  ["you-and", item12],
  ["beyond-ash", item13],
  ["made-in-trap", item14],
  ["otoge-rush", item15],
  ["senirenol-developers-hub", item16],
  ["unity-design-workshop", item17],
  ["unity-single-scene-template", item18],
  ["uraaka-management", item19],
  ["web-portfolio-frontend", item20],
] as const;
