// This file is auto-generated by scripts/generate-blog-content.mjs.
// Do not edit manually.

export type BlogArticleSource = {
  slug: string;
  raw: string;
};

export const blogArticleSources: BlogArticleSource[] = [
  { slug: "test", raw: "---\ntitle: \"Markdownテスト\"\ndate: \"2026-05-05\"\n---\n\n![](/images/icon.jpg)\n\nMarkdownテスト  \n末尾スペースによる改行テスト\n\n# H1 見出しテスト\n\n## H2 見出しテスト\n\n### H3 見出しテスト\n\n#### H4 見出しテスト\n\n##### H5 見出しテスト\n\n###### H6 見出しテスト\n\n---\n\n通常テキスト、**太字**、*強調*、~~取り消し線~~、`inline code`\n\n> 引用ブロック\n> 2行目\n\n:::info\n情報メッセージ\n:::\n\n:::warning\n警告メッセージ\n:::\n\n:::error\nエラーメッセージ\n:::\n\n:::success\n成功メッセージ\n:::\n\n## リスト\n\n- 箇条書きA\n- 箇条書きB\n- 箇条書きC\n\n1. 番号付きリスト1\n2. 番号付きリスト2\n3. 番号付きリスト3\n\n- [x] タスクリスト完了\n- [ ] タスクリスト未完了\n\n## リンク\n\n- 内部リンク: [Aboutページ](/about)\n- 外部リンク: [Next.js公式](https://nextjs.org/)\n\n## コード\n\n```ts\ntype User = {\n  id: string;\n  name: string;\n};\n\nconst user: User = { id: \"u1\", name: \"Kageki\" };\nconsole.log(user.name);\n```\n\n```bash\nnpm run dev\n```\n\n## 表\n\n| 項目 | 値 | メモ |\n| --- | --- | --- |\n| 見出し | h1-h6 | 全レベル確認 |\n| 文字装飾 | strong/em/del/code | インライン確認 |\n| GFM | table/task list | 表示確認 |\n| リンク | internal/external | 遷移確認 |\n\n" },
];
